Enable hugepages and VXLAN underlay NIC on Genesis
The OVS-DPDK blueprint currently uses vxlan and requies an
additional underlay network. This patch adds support for configuring
the corresponding NIC on the Genesis node.
Moreover, this patch adds support for enabling hugepages on the Genesis
node.

Change-Id: Ieaa2eebbcc112584f400cfaba8c1813e92014de3

diff --git a/firstboot-genesis.sh.template b/firstboot-genesis.sh.template
--- a/firstboot-genesis.sh.template
+++ b/firstboot-genesis.sh.template
@@ -171,5 +171,27 @@ END
     fi
 fi
 
+
+# Creating VXLAN interface
+
+if [ -n "@@SRV_VXLAN_INF@@" ]; then
+    echo "Configuring VXLAN Interface in the server"
+    tee -a /etc/network/interfaces << END
+
+# VXLAN
+auto @@SRV_VXLAN_INF@@
+iface @@SRV_VXLAN_INF@@ inet static
+address @@SRV_VXLAN_IP@@
+    netmask 255.255.255.0
+    mtu @@SRV_MTU@@
+END
+    ifup @@SRV_VXLAN_INF@@
+    if [ $? -eq 0 ]; then
+        echo " VXLAN interface Created"
+    else
+        echo " Failed to create VXLAN Interface"
+    fi
+fi
+
 exit
 
